/*
 Author: zerotrac
 Date: 2017/10/31
*/

#ifndef CONST_H
#define CONST_H

#define SOCKET_LISTEN_MAX 20
#define KQUEUE_MONITOR_MAX 50
#define RECEIVE_DATA_MAX 8192
#define USERNAME_MAX 128

#define LOGIN_NOUSERNAME 0
#define LOGIN_NOPASSWORD 1
#define LOGIN_SUCCESS    2

#define CLIENT_COMMAND_PIPE 0
#define CLIENT_ACCEPT_PIPE 1
#define CLIENT_FILE_PIPE 2

#define CONNECTION_NONE 0
#define CONNECTION_PORT 1
#define CONNECTION_PASV 2

#define STREAM_RETR 0
#define STREAM_STOR 1

#endif
